audit_header: false
title: "Omaha's Best Real Estate Training"
description: Tracy Frans, a top Real Estate Agent in Omaha, share our own internal real estate agent training for free. Their Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Ownership Opportunities
    url: #
  - title: Join Our Team
    url: http://tracyfrans.exprealty.careers/
  - title: Events
    url: /events/
  - title: Strategy Call
    url: /strategy-call/
client:
  name: Tracy and Brandon Frans
  title: CRS
  license_number:
  about_markdown: |
    “Be real. Be you. Enjoy. Maximize everything you are doing in life.”

    Tracy and Brandon Frans met in high school math class and have consistently pushed each other since. He’s always been an analytical type; Tracy is the energy bursting with creativity and can out run the energizer bunny any day. Their passion, enthusiasm and love for real estate is contagious. Mixing that with their progressive and forward thinking minds have allowed them to raise the bar of commitment to excellence. “We are constantly engaging in new ideas for better solutions and streamlining processes.”
  market: Omaha
  brand: eXp Realty
  brokerage:
  address: 7000 Olive Creek Rd Firth, NE 68358
  phone: 402-321-1111
  phone_type:
  phone2:
  phone2_type:
  email: tracy@tracyfrans.com
  url: http://AgentOwners.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how -- CLIENT BRAND -- can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TracyFransRealtorPro/
  linkedin_url: https://www.linkedin.com/in/tracy-frans-34548b29
  gplus_url:
  youtube_url:
  twitter_url: https://www.twitter.com/tracyfranshomes
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Omaha Real Estate Podcast with Tracy Frans'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Omaha Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional Omaha Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Omaha, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Tracy Frans'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo2.png
  logo_width_number: 60
  hero_text: Omaha Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#000000'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
